OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-d0pxojz9WwpNb90u4bA4215a5d004a4296E09a89E57e5251"
  base_url: "https://vip.apiyi.com/v1"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"